# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20160517_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='lat',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='lon',
            new_name='y',
        ),
    ]
