# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20160519_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
